# Configuration principale Spring Boot
spring:
  application:
    name: scalper-assistant

  profiles:
    active: dev

  # Configuration JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: false
        jdbc:
          time_zone: UTC
        temp:
          use_jdbc_metadata_defaults: false
    open-in-view: false

  # Configuration Jackson pour JSON
  jackson:
    serialization:
      write-dates-as-timestamps: false
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: non_null
    time-zone: UTC

  # Configuration Cache
  cache:
    type: redis
    redis:
      time-to-live: 300000 # 5 minutes

  # Configuration Task Scheduling
  task:
    scheduling:
      pool:
        size: 10
    execution:
      pool:
        core-size: 5
        max-size: 20
        queue-capacity: 100

# Configuration Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env,beans,configprops
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
    info:
      enabled: true
  info:
    env:
      enabled: true
    build:
      enabled: true
    git:
      enabled: true

  # Métriques personnalisées
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
      environment: ${spring.profiles.active}

# Configuration logging
logging:
  level:
    com.scalper: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%logger{50}] - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%logger{50}] - %msg%n"
  file:
    name: logs/scalper-assistant.log
    max-size: 100MB
    max-history: 30

# Configuration serveur
server:
  port: 8080
  servlet:
    context-path: /
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
  error:
    include-message: always
    include-binding-errors: always

# Configuration OpenAPI/Swagger
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
  info:
    title: Scalper Assistant API
    description: Assistant du Scalper Éclairé - Multi-Sessions Trading API
    version: 1.0.0

---
# Profil Development
spring:
  config:
    activate:
      on-profile: dev

  # Database locale
  datasource:
    url: jdbc:postgresql://localhost:5433/scalper_db
    username: scalper_user
    password: pass123
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  # Redis local
  redis:
    host: localhost
    port: 6379
    timeout: 2000ms
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 2

  # JPA Development
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# Configuration scalper pour développement
scalper:
  sessions:
    timezone: "UTC"
    asia:
      start-hour: 0
      end-hour: 6
    london:
      start-hour: 7
      end-hour: 11
    newyork:
      start-hour: 12
      end-hour: 16

  patterns:
    detection:
      enabled: true
      min-confidence: 0.6
    asia-breakout:
      min-range-pips: 15
      max-range-pips: 100
      volume-confirmation: true
    london-retest:
      max-time-since-break: 4 # heures
      min-level-importance: 0.7
    intra-session-bounce:
      min-rejection-pips: 3
      max-level-age: 12 # heures

  screenshots:
    enabled: true
    base-path: "./screenshots"
    driver: chrome
    headless: true
    timeout: 10

  telegram:
    enabled: false # Désactivé en dev
    bot-token: ""
    chat-id: ""

  news:
    enabled: true
    sources:
      - forexfactory
      - investing
    min-impact: HIGH

logging:
  level:
    com.scalper: DEBUG
    org.springframework.web: DEBUG

---
# Profil Docker
spring:
  config:
    activate:
      on-profile: docker

  # Database Docker
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:scalper_db}
    username: ${DB_USER:scalper_user}
    password: ${DB_PASS:pass123}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  # Redis Docker
  redis:
    host: ${REDIS_HOST:redis}
    port: ${REDIS_PORT:6379}
    timeout: 2000ms
    jedis:
      pool:
        max-active: 16
        max-idle: 8
        min-idle: 4

  # JPA Docker
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

# Configuration scalper pour Docker
scalper:
  sessions:
    timezone: "UTC"
    asia:
      start-hour: 0
      end-hour: 6
    london:
      start-hour: 7
      end-hour: 11
    newyork:
      start-hour: 12
      end-hour: 16

  patterns:
    detection:
      enabled: true
      min-confidence: 0.7
    asia-breakout:
      min-range-pips: 20
      max-range-pips: 80
      volume-confirmation: true
    london-retest:
      max-time-since-break: 3
      min-level-importance: 0.75
    intra-session-bounce:
      min-rejection-pips: 5
      max-level-age: 8

  screenshots:
    enabled: true
    base-path: "/app/screenshots"
    driver: chrome
    headless: true
    timeout: 15

  telegram:
    enabled: ${TELEGRAM_ENABLED:true}
    bot-token: ${TELEGRAM_BOT_TOKEN:}
    chat-id: ${TELEGRAM_CHAT_ID:}

  news:
    enabled: true
    sources:
      - forexfactory
      - investing
    min-impact: HIGH

  broker:
    enabled: ${BROKER_ENABLED:true}
    host: ${BROKER_HOST:localhost}
    port: ${BROKER_PORT:8001}
    login: ${BROKER_LOGIN:}
    password: ${BROKER_PASSWORD:}
    server: ${BROKER_SERVER:}

---
# Profil Production
spring:
  config:
    activate:
      on-profile: prod

  # Database Production
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  # Redis Production
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    timeout: 2000ms
    jedis:
      pool:
        max-active: 32
        max-idle: 16
        min-idle: 8

  # JPA Production
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

# Configuration scalper pour Production
scalper:
  sessions:
    timezone: "UTC"
    asia:
      start-hour: 0
      end-hour: 6
    london:
      start-hour: 7
      end-hour: 11
    newyork:
      start-hour: 12
      end-hour: 16

  patterns:
    detection:
      enabled: true
      min-confidence: 0.8
    asia-breakout:
      min-range-pips: 25
      max-range-pips: 70
      volume-confirmation: true
    london-retest:
      max-time-since-break: 2
      min-level-importance: 0.8
    intra-session-bounce:
      min-rejection-pips: 8
      max-level-age: 6

  screenshots:
    enabled: true
    base-path: "/app/screenshots"
    driver: chrome
    headless: true
    timeout: 20

  telegram:
    enabled: true
    bot-token: ${TELEGRAM_BOT_TOKEN}
    chat-id: ${TELEGRAM_CHAT_ID}

  news:
    enabled: true
    sources:
      - forexfactory
      - investing
    min-impact: HIGH

  broker:
    enabled: true
    host: ${BROKER_HOST}
    port: ${BROKER_PORT}
    login: ${BROKER_LOGIN}
    password: ${BROKER_PASSWORD}
    server: ${BROKER_SERVER}

logging:
  level:
    com.scalper: INFO
    org.springframework.web: WARN
    org.hibernate: WARN